cloudinary:
  api-key: 532389729736197
  api-secret: ${CLOUDINARY_SECRET}
  cloud-name: dislhsmj5
server:
  port: ${PORT:8080}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: topSecret_1
    url: ${JDBC_DATABASE_URL:}
    username: root
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 5MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB